[book]
title = "Markdown Memo"
authors = [ "reversed_R" ]
language = "ja"
src = "src"

# [preprocessor.autosummary]

[build]
create-missing = false

#use as mdbook preprocessor
# [preprocessor.auto-gen-summary]
# [preprocessor.autosummary]
# first-line-as-link-text = true # indicate mdbook to make the first line(default the file name) of markdown file as the link text in SUMMARY.md 

# [output.html.fold]
# enable = true
# level = 0
#
